services:
  mongo:
    image: mongo:6
    container_name: proshop-mongo
    command: mongod --quiet --logpath /dev/null
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks: [proshop-net]
    restart: unless-stopped

  # Chạy seed MỘT LẦN rồi thoát
  seed:
    build:
      context: .
      dockerfile: Dockerfile.backend
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/proshop
      - JWT_SECRET=${JWT_SECRET}
    command: ["npm", "run", "data:import"]
    networks: [proshop-net]
    restart: "no"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: proshop-backend
    depends_on:
      mongo:
        condition: service_healthy
      seed:
        condition: service_completed_successfully
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/proshop
      - JWT_SECRET=${JWT_SECRET}
      - PAYPAL_CLIENT_ID=${PAYPAL_CLIENT_ID:-sb}
      - PAGINATION_LIMIT=8
    ports:
      - "5000:5000"
    command: ["npm", "start"]   # dùng node, không cần nodemon
    networks: [proshop-net]
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: proshop-frontend
    depends_on:
      - backend
    ports:
      - "8081:8080"        # host:container (nginx listen 8080)
    networks: [proshop-net]
    restart: unless-stopped

networks:
  proshop-net:
    driver: bridge

volumes:
  mongo_data:
